<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.9.34" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.2" />
    <!-- Remove these two Rhino NuGet packages -->
    <!-- <PackageReference Include="Rhino3dm" Version="7.15.0" /> -->
    <!-- <PackageReference Include="RhinoCommon" Version="7.13.21348.13001" /> -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <!-- Add this new ItemGroup with direct reference to the Rhino8 DLL -->
  <ItemGroup>
    <Reference Include="RhinoCommon">
      <HintPath>..\lib\RhinoCommon.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\GrasshopperDefinitions\" />
  </ItemGroup>

</Project>